"""Push Service for Spin applications.

This module provides functionality to:
- Login to OCI container registries (ECR)
- Generate deterministic SHA256 tags from application content
- Push Spin applications to container registries

Requirements: 7.1, 7.2, 7.3, 7.4, 7.5, 7.6
"""

import base64
import hashlib
import subprocess
from dataclasses import dataclass
from pathlib import Path

try:
    import boto3
    BOTO3_AVAILABLE = True
except ImportError:
    BOTO3_AVAILABLE = False


@dataclass
class PushResult:
    """Result of a push operation.
    
    Attributes:
        success: True if push completed successfully
        image_uri: Full image URI with tag (if successful)
        error: Error message (if failed)
    """
    success: bool
    image_uri: str | None
    error: str | None


class PushService:
    """Service for pushing Spin applications to container registries.
    
    This service handles:
    1. Registry authentication via spin registry login
    2. Deterministic tag generation using SHA256
    3. Pushing applications via spin registry push
    
    Requirements: 7.1, 7.2, 7.3, 7.4, 7.5, 7.6
    """
    
    def generate_tag(self, app_dir: Path) -> str:
        """Generate a deterministic SHA256 tag from application content.
        
        Requirements: 7.4
        
        The tag is generated by hashing all files in the application directory
        in a deterministic order (sorted by path). This ensures that the same
        content always produces the same tag.
        
        Args:
            app_dir: Path to the application directory
            
        Returns:
            A 12-character hexadecimal string derived from SHA256 hash
        """
        hasher = hashlib.sha256()
        
        # Get all files in sorted order for deterministic hashing
        all_files = sorted(app_dir.rglob("*"))
        
        for file_path in all_files:
            if file_path.is_file():
                # Include relative path in hash for structure awareness
                relative_path = file_path.relative_to(app_dir)
                hasher.update(str(relative_path).encode('utf-8'))
                # Include file content
                hasher.update(file_path.read_bytes())
        
        # Return first 12 characters of hex digest
        return hasher.hexdigest()[:12]


    def _extract_registry_host(self, registry_url: str) -> str:
        """Extract just the registry hostname from a full image URL.

        For ECR, spin registry login needs just the host, not the repository.
        e.g., '217350599014.dkr.ecr.ap-northeast-2.amazonaws.com/repo' -> '217350599014.dkr.ecr.ap-northeast-2.amazonaws.com'

        Args:
            registry_url: Full registry URL possibly including repository

        Returns:
            Just the registry hostname
        """
        # Remove any tag if present
        url = registry_url.split(":")[0] if ":" in registry_url and "/" in registry_url.split(":")[1] else registry_url
        # Extract just the host (before first /)
        if "/" in url:
            return url.split("/")[0]
        return url

    def _get_ecr_credentials(self, registry_url: str) -> tuple[str, str] | None:
        """Get ECR credentials using IRSA (IAM Roles for Service Accounts).
        
        Uses boto3 to get ECR authorization token. IRSA automatically provides
        AWS credentials via environment variables injected by the EKS webhook.
        
        Args:
            registry_url: ECR registry URL
            
        Returns:
            Tuple of (username, password) if successful, None otherwise
        """
        if not BOTO3_AVAILABLE:
            return None
            
        try:
            # boto3 automatically uses IRSA credentials from environment
            ecr_client = boto3.client('ecr')
            
            # Get authorization token
            response = ecr_client.get_authorization_token()
            
            if not response.get('authorizationData'):
                return None
                
            auth_data = response['authorizationData'][0]
            auth_token = auth_data['authorizationToken']
            
            # Decode base64 token (format: username:password)
            decoded = base64.b64decode(auth_token).decode('utf-8')
            username, password = decoded.split(':', 1)
            
            return username, password
            
        except Exception:
            return None

    def login(self, registry_url: str, username: str | None = None, password: str | None = None) -> tuple[bool, str | None]:
        """Login to a container registry using spin registry login.
        
        For ECR registries, automatically uses IRSA credentials if username/password not provided.

        Requirements: 7.1, 7.5

        Args:
            registry_url: URL of the container registry (e.g., ECR URL)
            username: Registry username (optional for ECR with IRSA)
            password: Registry password (optional for ECR with IRSA)

        Returns:
            Tuple of (success, error_message)
            - success: True if login succeeded
            - error_message: Error details if failed, None otherwise
        """
        # Extract just the registry host for login (ECR needs host only, not repo)
        registry_host = self._extract_registry_host(registry_url)
        
        # If username/password not provided and this is ECR, try IRSA
        if not username or not password:
            if 'ecr' in registry_host and 'amazonaws.com' in registry_host:
                credentials = self._get_ecr_credentials(registry_url)
                if credentials:
                    username, password = credentials
                else:
                    return False, "Failed to get ECR credentials via IRSA. Ensure IAM role is properly configured."
            else:
                return False, "Username and password required for non-ECR registries"

        try:
            result = subprocess.run(
                [
                    "spin", "registry", "login",
                    "-u", username,
                    "-p", password,
                    registry_host
                ],
                capture_output=True,
                text=True,
                timeout=60  # 1 minute timeout for login
            )
            
            if result.returncode == 0:
                return True, None
            else:
                error_output = result.stderr or result.stdout
                return False, f"Registry login failed: {error_output}"
                
        except subprocess.TimeoutExpired:
            return False, "Registry login timed out after 60 seconds"
        except FileNotFoundError:
            return False, "spin CLI not found. Please ensure spin is installed and in PATH"
        except Exception as e:
            return False, f"Registry login failed: {str(e)}"

    def push(
        self,
        app_dir: Path,
        registry_url: str,
        tag: str | None = None
    ) -> PushResult:
        """Push a Spin application to a container registry.
        
        Requirements: 7.2, 7.3, 7.6
        
        Args:
            app_dir: Path to the application directory
            registry_url: URL of the container registry
            tag: Optional custom tag. If not provided, generates SHA256 tag.
            
        Returns:
            PushResult with success status, image_uri, or error message
        """
        # Generate tag if not provided
        if tag is None:
            tag = self.generate_tag(app_dir)
        
        # Construct full image URI
        image_uri = f"{registry_url}:{tag}"
        
        try:
            result = subprocess.run(
                ["spin", "registry", "push", image_uri],
                capture_output=True,
                text=True,
                cwd=str(app_dir),
                timeout=600  # 10 minute timeout for push
            )
            
            if result.returncode == 0:
                return PushResult(
                    success=True,
                    image_uri=image_uri,
                    error=None
                )
            else:
                error_output = result.stderr or result.stdout
                return PushResult(
                    success=False,
                    image_uri=None,
                    error=f"Push failed: {error_output}"
                )
                
        except subprocess.TimeoutExpired:
            return PushResult(
                success=False,
                image_uri=None,
                error="spin registry push timed out after 10 minutes"
            )
        except FileNotFoundError:
            return PushResult(
                success=False,
                image_uri=None,
                error="spin CLI not found. Please ensure spin is installed and in PATH"
            )
        except Exception as e:
            return PushResult(
                success=False,
                image_uri=None,
                error=f"Push failed: {str(e)}"
            )

    def full_push(
        self,
        app_dir: Path,
        registry_url: str,
        username: str | None = None,
        password: str | None = None,
        tag: str | None = None
    ) -> PushResult:
        """Execute the complete push pipeline: login and push.
        
        For ECR registries, automatically uses IRSA credentials if username/password not provided.
        
        Requirements: 7.1, 7.2, 7.3, 7.4, 7.5, 7.6
        
        Args:
            app_dir: Path to the application directory
            registry_url: URL of the container registry
            username: Registry username (optional for ECR with IRSA)
            password: Registry password (optional for ECR with IRSA)
            tag: Optional custom tag. If not provided, generates SHA256 tag.
            
        Returns:
            PushResult with success status, image_uri, or error message
        """
        # Step 1: Login to registry
        success, error = self.login(registry_url, username, password)
        if not success:
            return PushResult(
                success=False,
                image_uri=None,
                error=f"Registry login failed: {error}"
            )
        
        # Step 2: Push to registry
        return self.push(app_dir, registry_url, tag)
